# Analytics for Value Investing - Group Project
## S&P 500 Ex-Financials Quantitative Backtest (2010–2025)

**Team Members:**

<div style="display: inline-block">

| Name | Student ID | Main Role |
| :-------- | :-------- | :-------- |
| Kathryn Chan Hui | 01532587 | Development |
| Ng Hock Wah | 01513633 | Development |
| Liu Yi-Yi | 01548034 | Report |
| Liu Zhemin | 01525938 | Report |
| Zhang Tianrui | 01526062 | Slides |
| Ma Sunan | 01528539 | Slides |

</div>

**Course:** ACCT 656 - Analytics for Value Investing<br>
**Submission Date:** 19 June 2026

### Project Objective
To develop an investment strategy mimicking Warren Buffett’s value investing style using the Frazzini et al. (2018) methodology. 

### Rules & Constraints
* **Universe:** S&P 500 companies, strictly excluding all banks and financial institutions.
* **Time Horizon:** 16 years of data, ending no earlier than 2025 (2010–2025).
* **Data Frequency:** Strictly limited to monthly stock price/return data and annual financial/accounting data.

In [1]:
## IMPORT LIBRARIES

# General libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import timedelta
import time
import warnings
# Financial libraries
import yfinance as yf

# Suppress warnings for cleaner submission output
warnings.filterwarnings('ignore')
# Set plotting aesthetics for report-ready charts
plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)

## LOAD DATA

print("Loading project datasets...")
snp_raw = pd.read_csv("data/compustat_fundamental_annual.csv") # raw data from Compustat
sp500 = pd.read_csv("data/constituents.csv") # data of S&P 500 constituents

Loading project datasets...

### 1. Data preparation
Before conducting financial ratio analysis, the raw Compustat data has to be processed.
1. `costat` column was removed as there is only 1 unique value
2. Entries of `USD` currency (`curcd`) were kept, `CAD` entries were removed to prevent FX conversion issues and restrict the universe to the U.S. metrics
3. `datafmt`, `indfmt`, `consol` columns were removed as they are redundant database identifiers
4. `fyr` column was removed as we can calculate the fiscal year-end date using `datadate` column

In [2]:
# snp_raw["sic"].value_counts()

# --------------------------------------------------
# 1.1 Clean up raw Compustat data
# --------------------------------------------------

# Drop costat column since it is not relevant to our analysis
snp_raw.drop("costat", inplace=True, axis=1)
# Drop CAD since we dont want to convert it to USD
snp_raw.drop(snp_raw[snp_raw["curcd"] == "CAD"].index, inplace=True, axis=0)
# Drop curcd column since we only have USD data
snp_raw.drop("curcd", inplace=True, axis=1)
# Drop datafmt, indfmt and consol columns since they are not relevant to our analysis
snp_raw.drop(["datafmt", "indfmt", "consol"], inplace=True, axis=1)
# Drop fyr column since we can calculate fiscal year end date using datadate column
snp_raw.drop("fyr", inplace=True, axis=1)
snp_raw.head()

,gvkey,datadate,conm,tic,cik,naics,sic,at,ceq,che,...,ebit,ebitda,gp,ni,revt,sale,capx,oancf,csho,prcc_f
0,1004,31/5/2009,AAR CORP,AIR,1750.0,423860.0,5080,1377.511,656.895,112.505,...,125.529,166.080,313.299,78.651,1423.976,1423.976,27.535,64.451,38.884,14.70
1,1004,31/5/2010,AAR CORP,AIR,1750.0,423860.0,5080,1501.042,746.906,79.370,...,95.415,134.345,286.249,44.628,1352.151,1352.151,28.855,153.156,39.484,19.70
2,1004,31/5/2011,AAR CORP,AIR,1750.0,423860.0,5080,1703.727,835.845,57.433,...,137.016,196.312,367.711,69.826,1775.782,1775.782,124.879,108.598,39.781,26.39
3,1004,31/5/2012,AAR CORP,AIR,1750.0,423860.0,5080,2195.653,864.649,67.720,...,142.360,222.693,412.090,67.723,2074.498,2074.498,91.218,94.217,40.273,12.05
4,1004,31/5/2013,AAR CORP,AIR,1750.0,423860.0,5080,2136.900,918.600,75.300,...,136.600,245.200,452.600,55.000,2167.100,2167.100,37.600,162.900,39.382,20.06

As bank and financial institutions have different financial statement structure, we will drop them from our analysis. This is done by analysing the data of S&P 500 constituents to exclude GIC Sectors that are of value `Financials`. Following this, any banking-related companies using sub-industry keywords are removed.

It is noted that the number of companies reduced from 503 to 427 companies.

In [3]:
sp500.head() # check the first few rows

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989

In [4]:
# --------------------------------------------------
# 1.2 Remove companies under Financials sector
# --------------------------------------------------

sp500_nonfin = sp500[
    sp500["GICS Sector"] != "Financials"
].copy()

print("Original number of S&P 500 companies:", len(sp500))
print("After removing Financials:", len(sp500_nonfin))

Original number of S&P 500 companies: 503
After removing Financials: 427

In [5]:
# --------------------------------------------------
# 1.2 Remove banking-related companies using sub-industry keywords
# --------------------------------------------------

banking_keywords = [
    "bank",
    "banks",
    "banking",
    "financial",
    "insurance",
    "capital markets",
    "mortgage",
    "consumer finance",
    "diversified financial",
    "asset management",
    "investment banking",
    "brokerage"
]

pattern = "|".join(banking_keywords)
sp500_nonfin = sp500_nonfin[
    ~sp500_nonfin["GICS Sub-Industry"]
    .str.lower()
    .str.contains(pattern, na=False)
].copy()

print("After removing Financials and banking-related firms:", len(sp500_nonfin))

After removing Financials and banking-related firms: 427

We now create a Yahoo Finance-compatible ticker that cleans the symbol provided to create a standardised ticker that will be used to filter the data in `snp_raw`.

In [6]:
# --------------------------------------------------
# 1.3 Create Yahoo Finance-compatible ticker
# --------------------------------------------------

sp500_nonfin["ticker_yahoo"] = (
    sp500_nonfin["Symbol"]
    .astype(str)
    .str.strip()
    .str.upper()
    .str.replace(".", "-", regex=False)
)

sp500_nonfin[["Symbol", "ticker_yahoo", "Security", "GICS Sector", "GICS Sub-Industry"]].head()

,Symbol,ticker_yahoo,Security,GICS Sector,GICS Sub-Industry
0,MMM,MMM,3M,Industrials,Industrial Conglomerates
1,AOS,AOS,A. O. Smith,Industrials,Building Products
2,ABT,ABT,Abbott Laboratories,Health Care,Health Care Equipment
3,ABBV,ABBV,AbbVie,Health Care,Biotechnology
4,ACN,ACN,Accenture,Information Technology,IT Consulting & Other Services

Non-Financial tickers are now merged with `snp_raw` to keep only non-financial company entries

In [7]:
# --------------------------------------------------
# 1.4 Merge S&P 500 data with Yahoo Finance-compatible tickers
# --------------------------------------------------

snp500_overall = pd.merge(snp_raw, sp500_nonfin, left_on="tic", right_on="ticker_yahoo", how="inner")
snp500_overall.drop(["tic", "Symbol"], inplace=True, axis=1)
snp500_overall.head()

,gvkey,datadate,conm,cik,naics,sic,at,ceq,che,dlc,...,csho,prcc_f,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded,ticker_yahoo
0,1075,31/12/2009,PINNACLE WEST CAPITAL CORP,764622.0,2211.0,4911,11808.155,3316.109,145.378,431.408,...,101.435,36.58,Pinnacle West Capital,Utilities,Multi-Utilities,"Phoenix, Arizona",1999-10-04,764622,1985,PNW
1,1075,31/12/2010,PINNACLE WEST CAPITAL CORP,764622.0,2211.0,4911,12362.703,3683.327,110.188,648.479,...,108.770,41.45,Pinnacle West Capital,Utilities,Multi-Utilities,"Phoenix, Arizona",1999-10-04,764622,1985,PNW
2,1075,31/12/2011,PINNACLE WEST CAPITAL CORP,764622.0,2211.0,4911,13111.018,3821.850,33.583,477.435,...,109.246,48.18,Pinnacle West Capital,Utilities,Multi-Utilities,"Phoenix, Arizona",1999-10-04,764622,1985,PNW
3,1075,31/12/2012,PINNACLE WEST CAPITAL CORP,764622.0,2211.0,4911,13379.615,3972.806,26.202,215.003,...,109.743,50.98,Pinnacle West Capital,Utilities,Multi-Utilities,"Phoenix, Arizona",1999-10-04,764622,1985,PNW
4,1075,31/12/2013,PINNACLE WEST CAPITAL CORP,764622.0,2211.0,4911,13508.686,4194.470,9.526,693.549,...,110.182,52.92,Pinnacle West Capital,Utilities,Multi-Utilities,"Phoenix, Arizona",1999-10-04,764622,1985,PNW

In [8]:
# Store merged data to understand the data content
snp500_overall.to_csv("data/snp500_merged.csv", index=False)

### 2. Data cleaning
Before working with the data to calculate financial ratios, a quick review of the contents of the S&P 500 raw data from Compustat showed some entries having no financial data. If more than 25% of a row is missing, the firm-year observation is likely too incomplete to be reliable. To confirm the removal, this is done on a small sample of data where known entries are to be omitted.

After confirming this is the threshold to be used, the removal will be done on the whole dataset.

In [9]:
# --------------------------------------------------
# 2.1 Testing removal of entries with more than 25% missing values
# --------------------------------------------------

# Checking specific rows to confirm missing values are handled correctly
copy = snp500_overall.iloc[6840:6845].copy()
## we want to remove rows with more than 25% missing values, so we check rows around the 25% threshold
cleaned = copy[copy.isna().mean(axis=1) <= 0.25]
# Printed copy and cleaned to confirm that the correct rows are removed

In [10]:
# --------------------------------------------------
# 2.2 Conduct actual removal of entries with more than 25% missing values
# --------------------------------------------------

snp500_overall_cleaned = snp500_overall[snp500_overall.isna().mean(axis=1) <= 0.25]
print("Original number of rows:", len(snp500_overall))
print("Number of rows after cleaning:", len(snp500_overall_cleaned))
print("Number of rows removed:", len(snp500_overall) - len(snp500_overall_cleaned))

Original number of rows: 6878
Number of rows after cleaning: 6846
Number of rows removed: 32

Note: cross checked with excel, all 32 rows of empty data was removed

In [11]:
# Store cleaned data for analysis
snp500_overall_cleaned.to_csv("data/snp500_cleaned.csv", index=False)

### 3. Downloading Yahoo monthly stock returns
To evaluate performance and calculate market-based signals, monthly pricing data is required. The `yfinance` API is used to download monthly adjusted closing prices from 2009 to 2025 for the non-financial S&P 500 universe - established in Section 2.

*Note: The download deliberately begins in January 2009 to ensure we have a full trailing year of data to calculate lagged market signals (like 11-month Momentum) by the time the backtest officially begins in 2010. Any failed downloads (e.g., delisted tickers like FDXF) would be tracked and isolated for removal.*

In [12]:
# Load the cleaned S&P 500 data for analysis

snp500_cleaned = pd.read_csv("data/snp500_cleaned.csv")

tickers = (
    snp500_cleaned["ticker_yahoo"]
    .dropna()
    .astype(str)
    .str.strip()
    .str.upper()
    .unique()
    .tolist()
)

tickers = sorted(tickers)
print("Number of tickers:", len(tickers))

Number of tickers: 423

To calculate monthly stock returns, the filtered universe is iterated through to download historical pricing data using the `yfinance` API. The adjusted closing price is extracted with `auto_adjust=True`. This ensures that subsequent return calculations (using `pct_change()`) is accounted for. Any failed downloads due to delisted tickers are logged and excluded.

In [13]:
# --------------------------------------------------
# 3.1 Download monthly adjusted prices from Yahoo Finance
# --------------------------------------------------

all_monthly_data = []
failed_tickers = []

for i, ticker in enumerate(tickers, start=1):
    try:
        print(f"Downloading {i}/{len(tickers)}: {ticker}")

        data = yf.download(
            ticker,
            start="2009-01-01",
            end="2025-12-31",
            interval="1mo",
            auto_adjust=True,
            progress=False,
            multi_level_index=False
        )

        if data.empty:
            print(f"No data found for: {ticker}")
            failed_tickers.append(ticker)
            continue

        # Reset index so Date becomes a column
        data = data.reset_index()
        # Keep only date and adjusted close price
        temp = data[["Date", "Close"]].copy()

        temp["ticker_yahoo"] = ticker
        temp = temp.rename(columns={
            "Date": "month",
            "Close": "adjusted_close"
        })

        temp["month"] = pd.to_datetime(temp["month"])
        # Calculate monthly return ticker by ticker
        temp["monthly_return"] = temp["adjusted_close"].pct_change()

        all_monthly_data.append(
            temp[["ticker_yahoo", "month", "adjusted_close", "monthly_return"]]
        )

        time.sleep(0.3)

    except Exception as e:
        print(f"Failed to download {ticker}: {e}")
        failed_tickers.append(ticker)

Downloading 1/423: A
Downloading 2/423: AAPL
Downloading 3/423: ABBV
Downloading 4/423: ABNB
Downloading 5/423: ABT
Downloading 6/423: ACN
Downloading 7/423: ADBE
Downloading 8/423: ADI
Downloading 9/423: ADM
Downloading 10/423: ADP
Downloading 11/423: ADSK
Downloading 12/423: AEE
Downloading 13/423: AEP
Downloading 14/423: AES
Downloading 15/423: AKAM
Downloading 16/423: ALB
Downloading 17/423: ALGN
Downloading 18/423: ALLE
Downloading 19/423: AMAT
Downloading 20/423: AMCR
Downloading 21/423: AMD
Downloading 22/423: AME
Downloading 23/423: AMGN
Downloading 24/423: AMT
Downloading 25/423: AMZN
Downloading 26/423: ANET
Downloading 27/423: AOS
Downloading 28/423: APA
Downloading 29/423: APD
Downloading 30/423: APH
Downloading 31/423: APP
Downloading 32/423: APTV
Downloading 33/423: ARE
Downloading 34/423: ATO
Downloading 35/423: AVB
Downloading 36/423: AVGO
Downloading 37/423: AVY
Downloading 38/423: AWK
Downloading 39/423: AXON
Downloading 40/423: AZO
Downloading 41/423: BA
Downloading 42/423: BALL
Downloading 43/423: BAX
Downloading 44/423: BBY
Downloading 45/423: BDX
Downloading 46/423: BG
Downloading 47/423: BIIB
Downloading 48/423: BKNG
Downloading 49/423: BKR
Downloading 50/423: BLDR
Downloading 51/423: BMY
Downloading 52/423: BR
Downloading 53/423: BSX
Downloading 54/423: BXP
Downloading 55/423: CAG
Downloading 56/423: CAH
Downloading 57/423: CARR
Downloading 58/423: CASY
Downloading 59/423: CAT
Downloading 60/423: CBRE
Downloading 61/423: CCI
Downloading 62/423: CCL
Downloading 63/423: CDNS
Downloading 64/423: CDW
Downloading 65/423: CEG
Downloading 66/423: CF
Downloading 67/423: CHD
Downloading 68/423: CHRW
Downloading 69/423: CHTR
Downloading 70/423: CI
Downloading 71/423: CIEN
Downloading 72/423: CL
Downloading 73/423: CLX
Downloading 74/423: CMCSA
Downloading 75/423: CMG
Downloading 76/423: CMI
Downloading 77/423: CMS
Downloading 78/423: CNC
Downloading 79/423: CNP
Downloading 80/423: COHR
Downloading 81/423: COO
Downloading 82/423: COP
Downloading 83/423: COR
Downloading 84/423: COST
Downloading 85/423: CPB
Downloading 86/423: CPRT
Downloading 87/423: CPT
Downloading 88/423: CRH
Downloading 89/423: CRL
Downloading 90/423: CRM
Downloading 91/423: CRWD
Downloading 92/423: CSCO
Downloading 93/423: CSGP
Downloading 94/423: CSX
Downloading 95/423: CTAS
Downloading 96/423: CTSH
Downloading 97/423: CTVA
Downloading 98/423: CVNA
Downloading 99/423: CVS
Downloading 100/423: CVX
Downloading 101/423: D
Downloading 102/423: DAL
Downloading 103/423: DASH
Downloading 104/423: DD
Downloading 105/423: DDOG
Downloading 106/423: DE
Downloading 107/423: DECK
Downloading 108/423: DELL
Downloading 109/423: DG
Downloading 110/423: DGX
Downloading 111/423: DHI
Downloading 112/423: DHR
Downloading 113/423: DIS
Downloading 114/423: DLR
Downloading 115/423: DLTR
Downloading 116/423: DOC
Downloading 117/423: DOV
Downloading 118/423: DOW
Downloading 119/423: DPZ
Downloading 120/423: DRI
Downloading 121/423: DTE
Downloading 122/423: DUK
Downloading 123/423: DVA
Downloading 124/423: DVN
Downloading 125/423: DXCM
Downloading 126/423: EA
Downloading 127/423: EBAY
Downloading 128/423: ECL
Downloading 129/423: ED
Downloading 130/423: EFX
Downloading 131/423: EIX
Downloading 132/423: EL
Downloading 133/423: ELV
Downloading 134/423: EME
Downloading 135/423: EMR
Downloading 136/423: EOG
Downloading 137/423: EQIX
Downloading 138/423: EQR
Downloading 139/423: EQT
Downloading 140/423: ES
Downloading 141/423: ESS
Downloading 142/423: ETN
Downloading 143/423: ETR
Downloading 144/423: EVRG
Downloading 145/423: EW
Downloading 146/423: EXC
Downloading 147/423: EXE
Downloading 148/423: EXPD
Downloading 149/423: EXPE
Downloading 150/423: EXR
Downloading 151/423: F
Downloading 152/423: FANG
Downloading 153/423: FAST
Downloading 154/423: FCX
Downloading 155/423: FDX
Downloading 156/423: FDXF

$FDXF: possibly delisted; no price data found  (1mo 2009-01-01 -> 2025-12-31) (Yahoo error = "Data doesn't exist for startDate = 1230786000, endDate = 1767157200")

1 Failed download:
['FDXF']: possibly delisted; no price data found  (1mo 2009-01-01 -> 2025-12-31) (Yahoo error = "Data doesn't exist for startDate = 1230786000, endDate = 1767157200")

No data found for: FDXF
Downloading 157/423: FE
Downloading 158/423: FFIV
Downloading 159/423: FICO
Downloading 160/423: FIX
Downloading 161/423: FOXA
Downloading 162/423: FRT
Downloading 163/423: FSLR
Downloading 164/423: FTNT
Downloading 165/423: FTV
Downloading 166/423: GD
Downloading 167/423: GDDY
Downloading 168/423: GE
Downloading 169/423: GEHC
Downloading 170/423: GEN
Downloading 171/423: GEV
Downloading 172/423: GILD
Downloading 173/423: GIS
Downloading 174/423: GLW
Downloading 175/423: GM
Downloading 176/423: GNRC
Downloading 177/423: GOOGL
Downloading 178/423: GPC
Downloading 179/423: GRMN
Downloading 180/423: GWW
Downloading 181/423: HAL
Downloading 182/423: HAS
Downloading 183/423: HCA
Downloading 184/423: HD
Downloading 185/423: HII
Downloading 186/423: HLT
Downloading 187/423: HON
Downloading 188/423: HPE
Downloading 189/423: HPQ
Downloading 190/423: HRL
Downloading 191/423: HSIC
Downloading 192/423: HST
Downloading 193/423: HSY
Downloading 194/423: HUBB
Downloading 195/423: HUM
Downloading 196/423: HWM
Downloading 197/423: IBM
Downloading 198/423: IDXX
Downloading 199/423: IEX
Downloading 200/423: IFF
Downloading 201/423: INCY
Downloading 202/423: INTC
Downloading 203/423: INTU
Downloading 204/423: INVH
Downloading 205/423: IP
Downloading 206/423: IQV
Downloading 207/423: IR
Downloading 208/423: IRM
Downloading 209/423: ISRG
Downloading 210/423: IT
Downloading 211/423: ITW
Downloading 212/423: J
Downloading 213/423: JBHT
Downloading 214/423: JBL
Downloading 215/423: JCI
Downloading 216/423: JNJ
Downloading 217/423: KDP
Downloading 218/423: KEYS
Downloading 219/423: KHC
Downloading 220/423: KIM
Downloading 221/423: KLAC
Downloading 222/423: KMB
Downloading 223/423: KMI
Downloading 224/423: KO
Downloading 225/423: KR
Downloading 226/423: KVUE
Downloading 227/423: LDOS
Downloading 228/423: LEN
Downloading 229/423: LH
Downloading 230/423: LHX
Downloading 231/423: LII
Downloading 232/423: LIN
Downloading 233/423: LITE
Downloading 234/423: LLY
Downloading 235/423: LMT
Downloading 236/423: LNT
Downloading 237/423: LOW
Downloading 238/423: LRCX
Downloading 239/423: LULU
Downloading 240/423: LUV
Downloading 241/423: LVS
Downloading 242/423: LYB
Downloading 243/423: LYV
Downloading 244/423: MAA
Downloading 245/423: MAR
Downloading 246/423: MAS
Downloading 247/423: MCD
Downloading 248/423: MCHP
Downloading 249/423: MCK
Downloading 250/423: MDLZ
Downloading 251/423: MDT
Downloading 252/423: META
Downloading 253/423: MGM
Downloading 254/423: MKC
Downloading 255/423: MLM
Downloading 256/423: MMM
Downloading 257/423: MNST
Downloading 258/423: MO
Downloading 259/423: MOS
Downloading 260/423: MPC
Downloading 261/423: MPWR
Downloading 262/423: MRK
Downloading 263/423: MRNA
Downloading 264/423: MSFT
Downloading 265/423: MSI
Downloading 266/423: MTD
Downloading 267/423: MU
Downloading 268/423: NCLH
Downloading 269/423: NDSN
Downloading 270/423: NEE
Downloading 271/423: NEM
Downloading 272/423: NFLX
Downloading 273/423: NI
Downloading 274/423: NKE
Downloading 275/423: NOC
Downloading 276/423: NOW
Downloading 277/423: NRG
Downloading 278/423: NSC
Downloading 279/423: NTAP
Downloading 280/423: NUE
Downloading 281/423: NVDA
Downloading 282/423: NVR
Downloading 283/423: NWSA
Downloading 284/423: NXPI
Downloading 285/423: O
Downloading 286/423: ODFL
Downloading 287/423: OKE
Downloading 288/423: OMC
Downloading 289/423: ON
Downloading 290/423: ORCL
Downloading 291/423: ORLY
Downloading 292/423: OTIS
Downloading 293/423: OXY
Downloading 294/423: PANW
Downloading 295/423: PAYX
Downloading 296/423: PCAR
Downloading 297/423: PCG
Downloading 298/423: PEG
Downloading 299/423: PEP
Downloading 300/423: PFE
Downloading 301/423: PG
Downloading 302/423: PH
Downloading 303/423: PHM
Downloading 304/423: PKG
Downloading 305/423: PLD
Downloading 306/423: PLTR
Downloading 307/423: PM
Downloading 308/423: PNR
Downloading 309/423: PNW
Downloading 310/423: PODD
Downloading 311/423: POOL
Downloading 312/423: PPG
Downloading 313/423: PPL
Downloading 314/423: PSA
Downloading 315/423: PSKY
Downloading 316/423: PSX
Downloading 317/423: PTC
Downloading 318/423: PWR
Downloading 319/423: Q
Downloading 320/423: QCOM
Downloading 321/423: RCL
Downloading 322/423: REG
Downloading 323/423: REGN
Downloading 324/423: RL
Downloading 325/423: RMD
Downloading 326/423: ROK
Downloading 327/423: ROL
Downloading 328/423: ROP
Downloading 329/423: ROST
Downloading 330/423: RSG
Downloading 331/423: RTX
Downloading 332/423: RVTY
Downloading 333/423: SATS
Downloading 334/423: SBAC
Downloading 335/423: SBUX
Downloading 336/423: SHW
Downloading 337/423: SJM
Downloading 338/423: SLB
Downloading 339/423: SMCI
Downloading 340/423: SNA
Downloading 341/423: SNDK
Downloading 342/423: SNPS
Downloading 343/423: SO
Downloading 344/423: SOLV
Downloading 345/423: SPG
Downloading 346/423: SRE
Downloading 347/423: STE
Downloading 348/423: STLD
Downloading 349/423: STX
Downloading 350/423: STZ
Downloading 351/423: SW
Downloading 352/423: SWK
Downloading 353/423: SWKS
Downloading 354/423: SYK
Downloading 355/423: SYY
Downloading 356/423: T
Downloading 357/423: TAP
Downloading 358/423: TDG
Downloading 359/423: TDY
Downloading 360/423: TECH
Downloading 361/423: TEL
Downloading 362/423: TER
Downloading 363/423: TGT
Downloading 364/423: TJX
Downloading 365/423: TKO
Downloading 366/423: TMO
Downloading 367/423: TMUS
Downloading 368/423: TPL
Downloading 369/423: TPR
Downloading 370/423: TRGP
Downloading 371/423: TRMB
Downloading 372/423: TSCO
Downloading 373/423: TSLA
Downloading 374/423: TSN
Downloading 375/423: TT
Downloading 376/423: TTD
Downloading 377/423: TTWO
Downloading 378/423: TXN
Downloading 379/423: TXT
Downloading 380/423: TYL
Downloading 381/423: UAL
Downloading 382/423: UBER
Downloading 383/423: UDR
Downloading 384/423: UHS
Downloading 385/423: ULTA
Downloading 386/423: UNH
Downloading 387/423: UNP
Downloading 388/423: UPS
Downloading 389/423: URI
Downloading 390/423: VEEV
Downloading 391/423: VICI
Downloading 392/423: VLO
Downloading 393/423: VLTO
Downloading 394/423: VMC
Downloading 395/423: VRSK
Downloading 396/423: VRSN
Downloading 397/423: VRT
Downloading 398/423: VRTX
Downloading 399/423: VST
Downloading 400/423: VTR
Downloading 401/423: VTRS
Downloading 402/423: VZ
Downloading 403/423: WAB
Downloading 404/423: WAT
Downloading 405/423: WBD
Downloading 406/423: WDAY
Downloading 407/423: WDC
Downloading 408/423: WEC
Downloading 409/423: WELL
Downloading 410/423: WM
Downloading 411/423: WMB
Downloading 412/423: WMT
Downloading 413/423: WSM
Downloading 414/423: WST
Downloading 415/423: WY
Downloading 416/423: WYNN
Downloading 417/423: XEL
Downloading 418/423: XOM
Downloading 419/423: XYL
Downloading 420/423: YUM
Downloading 421/423: ZBH
Downloading 422/423: ZBRA
Downloading 423/423: ZTS

The monthly stock returns data are now concatenatedinto a single consolidated dataframe and sorted chronologically by company. To maintain data integrity for the remainder of the backtest, the cleaned monthly stock data and the list of failed downloads (e.g.: delisted tickers) into separate CSV files for further analysis and cross-referencing.

In [14]:
# --------------------------------------------------
# 3.2 Combine all downloaded monthly data
# --------------------------------------------------

monthly_stock_data = pd.concat(all_monthly_data, ignore_index=True)

monthly_stock_data = monthly_stock_data.sort_values(
    ["ticker_yahoo", "month"]
).reset_index(drop=True)

# Save clean monthly return file
monthly_stock_data.to_csv("data/yahoo_monthly_stock_returns_clean.csv", index=False)

# Save failed tickers
failed_df = pd.DataFrame({"failed_ticker": failed_tickers})
failed_df.to_csv("data/failed_yahoo_tickers.csv", index=False)

print("Monthly stock return file saved as: data/yahoo_monthly_stock_returns_clean.csv")
print("Failed ticker file saved as: data/failed_yahoo_tickers.csv")
print("Number of failed tickers:", len(failed_tickers))

Monthly stock return file saved as: data/yahoo_monthly_stock_returns_clean.csv
Failed ticker file saved as: data/failed_yahoo_tickers.csv
Number of failed tickers: 1

To ensure the integrity of the downloaded Yahoo Finance pricing data before constructing signals, a final review of the consolidated data is conducted. The following metrics are displayed:
- **Shape of data**: To note the total number of monthly-firm observations
- **Date range**: To verify the timeframe correctly spans the specified 2009 - 2025 horizon
- **Columns**: To verify the presence of required variables (`adjusted_close` and `monthly_return`) for upcoming analysis
- **Sample**: A preview of the first 20 chronological observations

In [15]:
# --------------------------------------------------
# 3.3 Validation checks
# --------------------------------------------------

print("Shape:", monthly_stock_data.shape)

print(f"\nDate range: {monthly_stock_data['month'].min()} to {monthly_stock_data['month'].max()}")
print(f"Number of tickers downloaded: {monthly_stock_data['ticker_yahoo'].nunique()}")
print(f"Columns: {monthly_stock_data.columns.tolist()}")

print("\nSample:")
monthly_stock_data.head(20)

Shape: (80285, 4)

Date range: 2009-01-01 00:00:00 to 2025-12-01 00:00:00
Number of tickers downloaded: 422
Columns: ['ticker_yahoo', 'month', 'adjusted_close', 'monthly_return']

Sample:

   ticker_yahoo      month  adjusted_close  monthly_return
0             A 2009-01-01       11.443534             NaN
1             A 2009-02-01        8.778863       -0.232854
2             A 2009-03-01        9.728271        0.108147
3             A 2009-04-01       11.557460        0.188028
4             A 2009-05-01       11.538472       -0.001643
5             A 2009-06-01       12.854987        0.114098
6             A 2009-07-01       14.696836        0.143279
7             A 2009-08-01       16.253860        0.105943
8             A 2009-09-01       17.614683        0.083723
9             A 2009-10-01       15.658914       -0.111031
10            A 2009-11-01       18.304586        0.168956
11            A 2009-12-01       19.665405        0.074343
12            A 2010-01-01       17.741280       -0.097843
13            A 2010-02-01       19.912251        0.122368
14            A 2010-03-01       21.766768        0.093134
15            A 2010-04-01       22.950363        0.054376
16            A 2010-05-01       20.481901       -0.107557
17            A 2010-06-01       17.994453       -0.121446
18            A 2010-07-01       17.677975       -0.017588
19            A 2010-08-01       17.070358       -0.034371

### 4. Aligning S&P 500 Universe (Removing failed tickers)
Before constructing financial signals, consistency should be established between the annual accounting data (Compustat) and the available monthly stock closing pricing data (Yahoo Finance).

By using the `failed_yahoo_tickers.csv` log, we can identify companies that lack pricing data (e.g.: delisted ticker `FDXF`) and remove their corresponding firm-year observations from the Compustat data.

The final universe has 422 tradeable S&P 500 companies.

In [16]:
# --------------------------------------------------
# 4.1 Load cleaned Compustat + S&P 500 file
# --------------------------------------------------

snp500_cleaned = pd.read_csv("data/snp500_cleaned.csv")

# --------------------------------------------------
# 4.2 Load failed Yahoo ticker file
# --------------------------------------------------

failed = pd.read_csv("data/failed_yahoo_tickers.csv")

failed_tickers = (
    failed["failed_ticker"]
    .dropna()
    .astype(str)
    .str.strip()
    .str.upper()
    .tolist()
)

print("Failed tickers:", failed_tickers)
print("Number of failed tickers:", len(failed_tickers))

# --------------------------------------------------
# 4.3 Remove failed tickers from Compustat/S&P 500 file
# --------------------------------------------------

snp500_cleaned2 = snp500_cleaned[
    ~snp500_cleaned["ticker_yahoo"].isin(failed_tickers)
].copy()

print("\nOriginal rows:", len(snp500_cleaned))
print("Rows after removing failed tickers:", len(snp500_cleaned2))
print("Rows removed:", len(snp500_cleaned) - len(snp500_cleaned2))
print("Original unique tickers:", snp500_cleaned["ticker_yahoo"].nunique())
print("Cleaned unique tickers:", snp500_cleaned2["ticker_yahoo"].nunique())

# Save final cleaned file
snp500_cleaned2.to_csv("data/snp500_cleaned_final.csv", index=False)
print("\nFinal cleaned file saved as: data/snp500_cleaned_final.csv")

Failed tickers: ['FDXF']
Number of failed tickers: 1

Original rows: 6846
Rows after removing failed tickers: 6844
Rows removed: 2
Original unique tickers: 423
Cleaned unique tickers: 422

Final cleaned file saved as: data/snp500_cleaned_final.csv

A set-based consistency check is done to mathematically prove that the accounting and pricing datasets contain the exact same universe of 422 tradeable S&P 500 companies.

In [17]:
# --------------------------------------------------
# 4.4 Check ticker consistency between accounting and return files
# --------------------------------------------------

accounting_tickers = set(snp500_cleaned2["ticker_yahoo"].dropna().unique())
return_tickers = set(monthly_stock_data["ticker_yahoo"].dropna().unique())

print("Tickers in accounting file:", len(accounting_tickers))
print("Tickers in monthly return file:", len(return_tickers))

print("Accounting tickers not in return file:")
print(accounting_tickers - return_tickers)

print("Return tickers not in accounting file:")
print(return_tickers - accounting_tickers)

Tickers in accounting file: 422
Tickers in monthly return file: 422
Accounting tickers not in return file:
set()
Return tickers not in accounting file:
set()

### 5. Final Accounting Data Preparation
Before creating the financial accounting signals, the raw Compustat data has to be properly formatted.

All columns are standardised, and rigorous coercion is done on essential accounting metrics into numeric values (using `pd.numeric()`) to prevent data type errors during calculation. A unified fiscal year (`fyear`) is created and sorted chronologically by company to prepare for the lagged factor calculations.

In [18]:
# ------------------------------------------------------------
# 5.1 Load final cleaned Compustat + S&P 500 data
# ------------------------------------------------------------

snp500 = pd.read_csv("data/snp500_cleaned_final.csv")

# Standardize column names
snp500.columns = snp500.columns.str.lower()
# Remove duplicate columns if any, e.g. duplicated cik
snp500 = snp500.loc[:, ~snp500.columns.duplicated()].copy()

# Convert datadate to datetime
snp500["datadate"] = pd.to_datetime(snp500["datadate"], errors="coerce")

# Create fiscal year if fyear is not available
if "fyear" not in snp500.columns:
    snp500["fyear"] = snp500["datadate"].dt.year

# ------------------------------------------------------------
# 5.2 Convert required columns to numeric
# ------------------------------------------------------------

numeric_cols = [
    "fyear", "at", "ceq", "seq", "txditc",
    "pstk", "pstkl", "pstkrv",
    "ni", "gp", "dlc", "dltt",
    "prcc_f", "csho"
]

for col in numeric_cols:
    if col in snp500.columns:
        snp500[col] = pd.to_numeric(snp500[col], errors="coerce")

# ------------------------------------------------------------
# 5.3 Sort data by company and fiscal year
# ------------------------------------------------------------

snp500 = snp500.sort_values(["ticker_yahoo", "fyear"]).copy()

### 6. Generating Financial Signals
Fundamental accounting metrics and factor signals are constructed to mimic a Buffett-style value and quality strategy, adapting Frazzini's methodology.

**6.1 Construct Book Equity**<br>
- Shareholders' Equity + Deferred Taxes (`txditc`) - Preferred Stock
- Preferred stock is calculated using a strict fallback hierarchy to maximize data retention.<br>(Redemption Value $\rightarrow$ Liquidating Value $\rightarrow$ Carrying Value)

**6.2 Construct Market Capitalization**<br>
- Closing Price (`prcc_f`) * Common Shares Outstanding (`csho`)
- Since Compustat reports shares in millions, the resulting market cap is in millions of USD.

**6.3 Construct Lagged Variables**<br>
To correctly calculate flow-over-stock ratios (like ROE) and year-over-year growth metrics, lagged variables are used. By grouping the data by ticker and using the `.shift(1)` function, the prior year's Total Assets and the Average Book Equity over the year are calculated.

**6.4 Construct the Core Factors**<br>
- **Value:** `Book-to-Market` (Book Equity / Market Cap) identifies companies trading at a discount to their net assets
- **Profitability / Quality:** `ROE` (Net Income / Avg Book Equity) and `Gross Profitability` measures how efficiently the firm generates earnings from its capital base
- **Safety / Risk:** `Leverage` (Total Debt / Total Assets) identifies firms with conservative capital structures
- **Growth:** `Asset Growth` captures the year-over-year expansion of the firm's asset base

In [ ]:
# ------------------------------------------------------------
# 6.1 Construct book equity
# ------------------------------------------------------------

# Preferred stock:
# Use redemption value first, then liquidating value, then carrying value

## 1. New column preferred_stock will start with pstkrv (redemption value)
snp500["preferred_stock"] = snp500["pstkrv"]
## 2. If pstkrv is missing, fill with pstkl (liquidating value)
if "pstkl" in snp500.columns:
    snp500["preferred_stock"] = snp500["preferred_stock"].fillna(snp500["pstkl"])
## 3. If both pstkrv and pstkl are missing, fill with pstk (carrying value)
if "pstk" in snp500.columns:
    snp500["preferred_stock"] = snp500["preferred_stock"].fillna(snp500["pstk"])
## 4. If all three are missing, fill with 0
snp500["preferred_stock"] = snp500["preferred_stock"].fillna(0)

# Deferred taxes and investment tax credit
snp500["txditc"] = snp500["txditc"].fillna(0)

# Book equity:
# Prefer SEQ; if missing, use CEQ
snp500["shareholders_equity"] = snp500["seq"].fillna(snp500["ceq"])

# Final book equity calculation:
## Book equity = shareholders' equity + deferred taxes and investment tax credit - preferred stock
snp500["book_equity"] = (
    snp500["shareholders_equity"]
    + snp500["txditc"]
    - snp500["preferred_stock"]
)

# ------------------------------------------------------------
# 6.2 Construct market capitalization
# ------------------------------------------------------------

# Compustat CSHO is usually in millions of shares
# PRCC_F is fiscal year-end price, Market cap is therefore in millions of USD
snp500["market_cap"] = snp500["prcc_f"] * snp500["csho"]

# ------------------------------------------------------------
# 6.3 Construct lagged variables
# ------------------------------------------------------------

snp500["lag_book_equity"] = snp500.groupby("ticker_yahoo")["book_equity"].shift(1)
snp500["avg_book_equity"] = (snp500["book_equity"] + snp500["lag_book_equity"]) / 2
snp500["lag_at"] = snp500.groupby("ticker_yahoo")["at"].shift(1)

# ------------------------------------------------------------
# 6.4 Generate financial signals
# ------------------------------------------------------------

# 1. Book-to-market
snp500["book_to_market"] = snp500["book_equity"] / snp500["market_cap"]
# 2. ROE
snp500["roe"] = snp500["ni"] / snp500["avg_book_equity"]
# 3. Gross profitability
snp500["gross_profitability"] = snp500["gp"] / snp500["at"]

# 4. Leverage
snp500["dlc"] = snp500["dlc"].fillna(0)
snp500["dltt"] = snp500["dltt"].fillna(0)
snp500["total_debt"] = snp500["dlc"] + snp500["dltt"]
snp500["leverage"] = snp500["total_debt"] / snp500["at"]

# 5. Asset growth
snp500["asset_growth"] = (snp500["at"] - snp500["lag_at"]) / snp500["lag_at"]

```python
# 1. Load the cleaned S&P 500 annual accounting data (ex-financials)
# Note: Ensure datadate is parsed as datetime
snp500_annual = pd.read_csv("data/snp500_cleaned_final.csv")
snp500_annual['datadate'] = pd.to_datetime(snp500_annual['datadate'], errors="coerce")

# 2. Load the cleaned Yahoo Finance monthly stock returns
monthly_returns = pd.read_csv("data/yahoo_monthly_stock_returns_clean.csv")
monthly_returns['month'] = pd.to_datetime(monthly_returns['month'])

print(f"Annual Accounting Records: {len(snp500_annual)}")
print(f"Monthly Return Records: {len(monthly_returns)}")
print("Data loaded successfully. Ready for signal generation.")
```